import "ImageMonitor.idl";
import "StagedImages.idl";

namespace PhotobookRuntimeComponent {

runtimeclass ImageViews
{
  ImageMonitor ImageMonitor();
  StagedImages StagedImages();
}
} // namespace PhotobookRuntimeComponent
