import "VirtualImagePtr.idl";
import "Int32Pair.idl";

namespace PhotobookRuntimeComponent {

runtimeclass ProcessingData
{
  String KeyPath();
  String Resource();
  UInt32 Position();
}

runtimeclass RowProcessingData
{
  String                  Root();
  IVector<ProcessingData> Images();
}

runtimeclass ImageMonitor
{
  void AddRow(String path, IVector<VirtualImagePtr> images);
  void RemoveRowByIndex(Int32 index);
  void RemoveRowByPath(String path);

  void Clear();

  void    CompleteRow(Int32 index);
  Boolean IsPendingByPath(String path);
  Boolean IsPendingByIndex(Int32 index);

  UInt32  ImportListSize();
  UInt32  RowSize(UInt32 row);
  UInt32  RowIndex(String path);
  Boolean ContainsRow(String path, Boolean subPath);
  String  RowPath(UInt32 row);

  IVector<String> RowList();

  VirtualImagePtr Image(UInt32 row, UInt32 index, String thumbnailsLocation);
  VirtualImagePtr Image(String full, String thumbnailsLocation);
  Int32Pair       Position(String full);

  IVector<IVector<VirtualImagePtr> > Unstaged(String thumbnailsLocation);
}
} // namespace PhotobookRuntimeComponent