
namespace PhotobookRuntimeComponent {

runtimeclass ImageResources
{
  String FullPath { get; };
  String MediumPath { get; };
  String SmallPath { get; };
}
} // namespace PhotobookRuntimeComponent
