
namespace PhotobookRuntimeComponent {
runtimeclass ImageUIData
{
  ImageUIData();
  ImageUIData(String keyPath, String full, String medium, String smallPath,
              Boolean processed);
  String  KeyPath { get; };
  String  FullPath { get; };
  String  MediumPath { get; };
  String  SmallPath { get; };
  Boolean Processed { get; };
}
} // namespace PhotobookRuntimeComponent
