namespace PhotobookRuntimeComponent {

enum PaperType {
  None,
  A4_Landscape,
  A4_Portrait,
  A5_Landscape,
  A5_Portrait,
  A3_Landscape,
  A3_Portrait,
  Custom,
  Square_Paper
};

runtimeclass PaperSettings
{
  PaperType Type
  {
    get;
    set;
  };
  Int32 Ppi
  {
    get;
    set;
  };
  Int32 Width
  {
    get;
    set;
  };
  Int32 Height
  {
    get;
    set;
  };
}
} // namespace PhotobookRuntimeComponent
