namespace PhotobookRuntimeComponent {

enum PBErrorCode {
  Unknown,
  FileDoesNotExist,
  NotADirectory,
  CorruptPersistenceFile,
  SQLiteError,

  FolderAlreadyImported,
  JSONParseError,

  NoImages,
  CannotExport
};

runtimeclass PBError
{
  String      description();
  PBErrorCode errorCode();
}
} // namespace PhotobookRuntimeComponent
