
namespace PhotobookRuntimeComponent {

// TODO: Change the filters to have idl at the top, not cpp
[default_interface] runtimeclass PhotobookWin {
  PhotobookWin();
  void recallMetadata();
  void recallProject(String name);

  void newProject(String name);
}
} // namespace PhotobookRuntimeComponent