import "PBError.idl";
import "VirtualImagePtr.idl";
import "ProgressInfo.idl";
import "LutIconInfo.idl";

namespace PhotobookRuntimeComponent {

delegate void Functor();

interface PhotobookListener
{
  void OnProjectRead();

  void OnMetadataUpdated(String focusedProjectName);
  void OnPersistenceError(PBError error);

  void OnExportFinished();
  void OnError(PBError error);

  void OnStagedImageRemoved(IVector<UInt32> removedIndexes);

  void OnMappingStarted(String path);
  void OnMappingFinished(String path);
  void OnMappingAborted(String path);

  void OnImageUpdated(String root, Int32 row, Int32 index);

  void OnProgressUpdate(ProgressInfo progress);

  void OnCollageThumbnailsCreated();

  void OnCollageCreated(VirtualImagePtr newImage);

  void OnImageMapped(Guid imageId, VirtualImagePtr image);

  void OnLutAdded(LutIconInfo lutIconInfo);

  void Post(Functor f);
};
} // namespace PhotobookRuntimeComponent
