import "PBError.idl";
import "ImageViews.idl";
import "PhotobookListener.idl";

namespace PhotobookRuntimeComponent {

// TODO: Change the filters to have idl at the top, not cpp
runtimeclass PhotobookWin
{
  PhotobookWin(String localStatePath, String installPath);

  void ConfigurePhotobookListener(PhotobookListener listener);

  void RecallMetadata();
  void RecallProject(String name);

  void NewProject(String name);
  void UnloadProject();

  void AddImportFolder(String importPath);
  void RemoveImportFolder(String path);

  ImageViews GetImageViews();

  void ExportPDFAlbum(String name, String path);
  void ExportPDFLibharu(String name, String path);
  void ExportJPGAlbum(String name, String path);
}
} // namespace PhotobookRuntimeComponent