namespace PhotobookRuntimeComponent {

enum JobType {
  None,
  Map,
  ThumbnailsProcess,
  ExportPdf,
  ExportJpg,
  Full,
  ExportLibharu
};

enum ProgressType { None, Defined, Undefined };

runtimeclass ProgressInfo
{
  JobType      jobType();
  ProgressType progressType();
  Int32        progress();
  Int32        progressCap();
  IVector<String> jobsProgress();
}
} // namespace PhotobookRuntimeComponent
