
namespace PhotobookRuntimeComponent {

[default_interface] runtimeclass ProjectItem {
  ProjectItem();
  ProjectItem(String itemId, String fullPath, String name);
  /*
  String ItemId { get; };
  String FullPath { get; };
  String Name { get; };
  */
}

} // namespace PhotobookRuntimeComponent