import "VirtualImagePtr.idl";
import "ProjectMetadataEntry.idl";
import "PaperSettings.idl";

namespace PhotobookRuntimeComponent {

runtimeclass Settings
{
  /*
  std::shared_ptr<Project> currentProject();
  */
  void RecallProject(String projectId);

  void RecallProjectByName(String name);

  void RecallMetadata();

  String ProjectId(String name);

  Boolean HasUUID(String name);

  IVector<String> ProjectsNames();

  // void newProject(String name, std::shared_ptr<Project> project);

  void RemoveById(String projectId);
  void RemoveByPath(String path);

  void Clear();

  Boolean Contains(String name);

  // std::vector<std::tuple<boost::uuids::uuid, std::string, Path>>
  // projectsList()
  //     const;

  IVector<ProjectMetadataEntry> ProjectsList();

  void Rename(String newName, String oldName);

  void Save(String                            thumbnailsDirectoryName,
            IVector<IVector<VirtualImagePtr> > unstagedImages,
            IVector<VirtualImagePtr> stagedImages, IVector<String> root);

  Boolean HasProjectOpen();
  String  CurrentProjectUUID();

  Boolean IsSaved(IVector<IVector<VirtualImagePtr> > unstagedImages,
                  IVector<VirtualImagePtr> stagedImages, IVector<String> roots);
  String  Hash(String path);

  PaperSettings GetPaperSettings();
}

} // namespace PhotobookRuntimeComponent
