import "VirtualImagePtr.idl";
import "ProjectMetadataEntry.idl";
import "PaperSettings.idl";

namespace PhotobookRuntimeComponent {

runtimeclass Settings
{
  /*
  std::shared_ptr<Project> currentProject();
  */
  void RecallProject(String projectId);

  void RecallProjectByName(String name);

  void RecallMetadata();

  String ProjectId(String name);

  Boolean HasUUID(String name);

  IVector<String> ProjectsNames();

  void NewProject(PaperSettings paperSettings);

  void RemoveById(String projectId);

  void Clear();

  Boolean Contains(String name);

  // std::vector<std::tuple<boost::uuids::uuid, std::string, Path>>
  // projectsList()
  //     const;

  IVector<ProjectMetadataEntry> ProjectsList();

  void Rename(String newName, String oldName);

  void Save();

  Boolean HasProjectOpen();
  String  CurrentProjectUUID();

  String  Hash(String path);

  PaperSettings GetPaperSettings();
}

} // namespace PhotobookRuntimeComponent
