import "VirtualImagePtr.idl";

namespace PhotobookRuntimeComponent {

runtimeclass VICollectionStatefulIterator
{
  VirtualImagePtr current();

  VICollectionStatefulIterator At(UInt32 index);

  UInt32 Size();

  Boolean Valid();
}

} // namespace PhotobookRuntimeComponent