import "ImageResources.idl";
import "Int32Pair.idl";

namespace PhotobookRuntimeComponent {

enum VirtualImageType { None, Text, Regular, Test };

runtimeclass VirtualImagePtr
{
  VirtualImageType Imagetype();

  ImageResources Frontend { get; };

  void GalleryProjection(ref UInt8[] buffer, Int32 portviewWidth,
                         Int32 portviewHeight, String thumbnailsPath);
}
} // namespace PhotobookRuntimeComponent
