import "PhotoBookListener.idl";

namespace CppWinRTProjection {

runtimeclass PhotoBook
{
  PhotoBook(PhotoBookListener listener);
  void AddMedia(String path);
  void setOutputPath(String path);
}
} // namespace CppWinRTProjection
