import "PhotoBookListener.idl";

namespace CppWinRTProjection {

runtimeclass PhotoBook
{
  PhotoBook();
  void AddMedia(String path);
  void setOutputPath(String path);

  void SetListener(PhotoBookListener listener);
}
} // namespace CppWinRTProjection
