// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace PhotobookUI
{
    [default_interface] runtimeclass Dashboard : Microsoft.UI.Xaml.Controls.Page
    {
      Dashboard();
    }
}
