
namespace PhotobookUI {
runtimeclass ImageUIData
{
  ImageUIData();
  ImageUIData(String fullPath, String mediumPath, String smallPath);
  String FullPath { get; };
  String MediumPath { get; };
  String SmallPath { get; };
}
} // namespace PhotobookUI
