// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace PhotobookUI
{
    [default_interface]
    runtimeclass TableContentPage : Microsoft.UI.Xaml.Controls.Page
    {
        TableContentPage();

        Int32 CanvasWidth { get; };
        Int32 CanvasHeight { get; };
    }
}
